export enum TaskType {
  FunCaptchaTask = 'FunCaptchaTask',
  GeeTestTask = 'GeeTestTask',
  HCaptchaTaskProxyless = 'HCaptchaTaskProxyless',
  HCaptchaTask = 'HCaptchaTask',
  ImageToTextTask = 'ImageToTextTask',
  RecaptchaV2EnterpriseTask = 'RecaptchaV2EnterpriseTask',
  NoCaptchaTaskProxyless = 'NoCaptchaTaskProxyless',
  NoCaptchaTask = 'NoCaptchaTask',
  RecaptchaV3TaskProxyless = 'RecaptchaV3TaskProxyless',
  TurnstileTask = 'TurnstileTask',
  ComplexImageTask = 'ComplexImageTask',
  CustomTask = 'CustomTask',
  AmazonTask = 'AmazonTask',
  BinanceTask = 'BinanceTask',
}
