export enum TaskType {
  FunCaptchaTaskProxyless = 'FunCaptchaTaskProxyless',
  FunCaptchaTask = 'FunCaptchaTask',
  GeeTestTaskProxyless = 'GeeTestTaskProxyless',
  GeeTestTask = 'GeeTestTask',
  HCaptchaTaskProxyless = 'HCaptchaTaskProxyless',
  HCaptchaTask = 'HCaptchaTask',
  ImageToTextTask = 'ImageToTextTask',
  RecaptchaV2EnterpriseTaskProxyless = 'RecaptchaV2EnterpriseTaskProxyless',
  RecaptchaV2EnterpriseTask = 'RecaptchaV2EnterpriseTask',
  NoCaptchaTaskProxyless = 'NoCaptchaTaskProxyless',
  NoCaptchaTask = 'NoCaptchaTask',
  RecaptchaV3TaskProxyless = 'RecaptchaV3TaskProxyless',
  TurnstileTask = 'TurnstileTask',
  TurnstileTaskProxyless = 'TurnstileTaskProxyless',
  ComplexImageTask = 'ComplexImageTask',
  CustomTask = 'CustomTask',
}
